### ISSUE TITLE
背景画像の平行移動と拡大縮小を可能にする

### ISSUE THREAD

**Issue by monman53** [monman53/exstitch#5]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

* [x] 平行移動 https://github.com/monman53/exstitch/commit/aea5142e0e45af0b2f8a2b615af1f3573ccc4336
* [x] 拡大縮小 https://github.com/monman53/exstitch/commit/b5ec8c44faa03270c48b9cafcbb63cc53b7b3ed3

**Comment by muatotto** [comment]
#37  にて完了したのでcloseします。
